import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

   docs: [{type: 'autogenerated', dirName: '.'}]
  // docs: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: '🎯 Vue d\'ensemble',
  //     items: [
  //       'overview/architecture',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '🔄 CI/CD',
  //     items: [
  //       'cicd/pipelines-java',
  //       'cicd/pipelines-drupal',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '🅰️ Frontend Angular',
  //     items: [
  //       'frontend/angular-cicd',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '🔒 Sécurité',
  //     items: [
  //       'security/trivy',
  //       'security/sbom',
  //       'owasp/owasp-top-10',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '🐳 Container Registry',
  //     items: [
  //       'docker-registry/harbor',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '🏗️ Infrastructure as Code',
  //     items: [
  //       {
  //         type: 'category',
  //         label: '📦 Terraform',
  //         items: [
  //           'iac/terraform/terraform-aws',
  //         ],
  //       },
  //       {
  //         type: 'category',
  //         label: '⚙️ Ansible',
  //         items: [
  //           'iac/ansible/ansible-multicloud',
  //           'iac/ansible/awx-orchestration',
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '📈 Observabilité',
  //     items: [
  //       'observability/prometheus-grafana',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '🔧 Outils',
  //     items: [
  //       'tools/renovate',
  //     ],
  //   },
  // ],
};

export default sidebars;